// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function missingArg(argv) {
  return argv.length < 4;
}

function stringToInt(value) {
  var value$1 = Belt_Int.fromString(value);
  if (value$1 !== undefined) {
    return value$1;
  } else {
    return -1;
  }
}

function removeEle(arr, index) {
  return Belt_Array.keepWithIndex(arr, (function (param, i) {
                return i !== index;
              }));
}

var getDate = (function() {
  let date = new Date();
  return new Date(date.getTime() - (date.getTimezoneOffset() * 60000))
    .toISOString()
    .split("T")[0];
});

exports.missingArg = missingArg;
exports.stringToInt = stringToInt;
exports.removeEle = removeEle;
exports.getDate = getDate;
/* No side effect */
