// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function removeEle(arr, index) {
  return Belt_Array.keepWithIndex(arr, (function (param, i) {
                return i !== index;
              }));
}

var getDate = (function() {
  let date = new Date();
  return new Date(date.getTime() - (date.getTimezoneOffset() * 60000))
    .toISOString()
    .split("T")[0];
});

exports.removeEle = removeEle;
exports.getDate = getDate;
/* No side effect */
