// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var TodoManager = require("./todoManager.bs.js");

var todo_path = "todo.txt";

var done_path = "done.txt";

if (process.argv.length <= 2) {
  TodoManager.showHelp(undefined);
} else {
  var cmd = Caml_array.get(process.argv, 2).trim().toLowerCase();
  switch (cmd) {
    case "add" :
        TodoManager.addTodo(todo_path);
        break;
    case "del" :
        TodoManager.delTodo(todo_path);
        break;
    case "done" :
        TodoManager.doneTodo(todo_path, done_path);
        break;
    case "help" :
        TodoManager.showHelp(undefined);
        break;
    case "ls" :
        TodoManager.showTodo(todo_path);
        break;
    case "report" :
        TodoManager.showReport(todo_path, done_path);
        break;
    default:
      TodoManager.showHelp(undefined);
  }
}

exports.todo_path = todo_path;
exports.done_path = done_path;
/*  Not a pure module */
