// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Os = require("os");
var Helper = require("./helper.bs.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var FileManager = require("./fileManager.bs.js");

var todoPath = "todo.txt";

var donePath = "done.txt";

function addTodo(todoText) {
  if (todoText !== undefined) {
    FileManager.appendTodos([todoText], todoPath);
    console.log("Added todo: \"" + todoText + "\"");
  } else {
    console.log("Error: Missing todo string. Nothing added!");
  }
  
}

function showTodo(param) {
  var todos = FileManager.loadTodos(todoPath);
  var todosCount = todos.length;
  if (todos.length === 0) {
    console.log("There are no pending todos!");
  } else {
    console.log(Belt_Array.reduceWithIndex(Belt_Array.reverse(todos), "", (function (acc, todo, index) {
                  return acc + ("[" + String(todosCount - index | 0) + "] " + todo) + Os.EOL;
                })).trim());
  }
  
}

function delTodo(todoId) {
  if (todoId !== undefined) {
    var todoIndex = todoId - 1 | 0;
    var todos = FileManager.loadTodos(todoPath);
    if (todos.length === 0 || todoIndex < 0 || todoIndex >= todos.length) {
      console.log("Error: todo #" + String(todoIndex + 1 | 0) + " does not exist. Nothing deleted.");
      return ;
    }
    var todos$1 = Helper.removeEle(todos, todoIndex);
    FileManager.writeTodos(todos$1, todoPath);
    console.log("Deleted todo #" + String(todoId));
    return ;
  }
  console.log("Error: Missing NUMBER for deleting todo.");
  
}

function doneTodo(todoId) {
  if (todoId !== undefined) {
    var todoIndex = todoId - 1 | 0;
    var todos = FileManager.loadTodos(todoPath);
    if (todos.length === 0 || todoIndex < 0 || todoIndex >= todos.length) {
      console.log("Error: todo #" + String(todoIndex + 1 | 0) + " does not exist.");
      return ;
    }
    var doneTodo$1 = Caml_array.get(todos, todoIndex);
    var todos$1 = Helper.removeEle(todos, todoIndex);
    FileManager.writeTodos(todos$1, todoPath);
    var parsedDoneTodo = "x " + Helper.getDate(undefined) + " " + doneTodo$1;
    FileManager.appendTodos([parsedDoneTodo], donePath);
    console.log("Marked todo #" + String(todoId) + " as done.");
    return ;
  }
  console.log("Error: Missing NUMBER for marking todo as done.");
  
}

function showHelp(param) {
  console.log("Usage :-\n$ ./todo add \"todo item\"  # Add a new todo\n$ ./todo ls               # Show remaining todos\n$ ./todo del NUMBER       # Delete a todo\n$ ./todo done NUMBER      # Complete a todo\n$ ./todo help             # Show usage\n$ ./todo report           # Statistics");
  
}

function showReport(param) {
  var todoCount = FileManager.loadTodos(todoPath).length;
  var doneCount = FileManager.loadTodos(donePath).length;
  console.log(Helper.getDate(undefined) + " Pending : " + String(todoCount) + " Completed : " + String(doneCount));
  
}

exports.todoPath = todoPath;
exports.donePath = donePath;
exports.addTodo = addTodo;
exports.showTodo = showTodo;
exports.delTodo = delTodo;
exports.doneTodo = doneTodo;
exports.showHelp = showHelp;
exports.showReport = showReport;
/* os Not a pure module */
