// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Os = require("os");
var Helper = require("./helper.bs.js");
var Process = require("process");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var FileManager = require("./fileManager.bs.js");

function addTodo(path) {
  if (Helper.missingArg(Process.argv)) {
    console.log("Error: Missing todo string. Nothing added!");
    return ;
  }
  var todoText = Caml_array.get(Process.argv, 3);
  FileManager.appendTodos([todoText], path);
  console.log("Added todo: \"" + todoText + "\"");
  
}

function showTodo(path) {
  var todos = FileManager.loadTodos(path);
  if (todos.length === 0) {
    console.log("There are no pending todos!");
    return ;
  }
  var todos$1 = Belt_Array.reverse(Belt_Array.mapWithIndex(todos, (function (index, todo) {
              return "[" + String(index + 1 | 0) + "] " + todo;
            })));
  console.log(todos$1.join(Os.EOL));
  
}

function delTodo(path) {
  if (Helper.missingArg(Process.argv)) {
    console.log("Error: Missing NUMBER for deleting todo.");
    return ;
  }
  var todoIndex = Helper.stringToInt(Caml_array.get(Process.argv, 3)) - 1 | 0;
  var todos = FileManager.loadTodos(path);
  if (todos.length === 0 || todoIndex < 0 || todoIndex >= todos.length) {
    console.log("Error: todo #" + String(todoIndex + 1 | 0) + " does not exist. Nothing deleted.");
    return ;
  }
  var todos$1 = Helper.removeEle(todos, todoIndex);
  FileManager.writeTodos(todos$1, path);
  console.log("Deleted todo #" + String(todoIndex + 1 | 0));
  
}

function doneTodo(todoPath, donePath) {
  if (Helper.missingArg(Process.argv)) {
    console.log("Error: Missing NUMBER for marking todo as done.");
    return ;
  }
  var todoIndex = Helper.stringToInt(Caml_array.get(Process.argv, 3)) - 1 | 0;
  var todos = FileManager.loadTodos(todoPath);
  if (todos.length === 0 || todoIndex < 0 || todoIndex >= todos.length) {
    console.log("Error: todo #" + String(todoIndex + 1 | 0) + " does not exist.");
    return ;
  }
  var doneTodo$1 = Caml_array.get(todos, todoIndex);
  var todos$1 = Helper.removeEle(todos, todoIndex);
  FileManager.writeTodos(todos$1, todoPath);
  var parsedDoneTodo = "x " + Helper.getDate(undefined) + " " + doneTodo$1;
  FileManager.appendTodos([parsedDoneTodo], donePath);
  console.log("Marked todo #" + String(todoIndex + 1 | 0) + " as done.");
  
}

function showHelp(param) {
  console.log("Usage :-\n$ ./todo add \"todo item\"  # Add a new todo\n$ ./todo ls               # Show remaining todos\n$ ./todo del NUMBER       # Delete a todo\n$ ./todo done NUMBER      # Complete a todo\n$ ./todo help             # Show usage\n$ ./todo report           # Statistics");
  
}

function showReport(todoPath, donePath) {
  var todoCount = FileManager.loadTodos(todoPath).length;
  var doneCount = FileManager.loadTodos(donePath).length;
  console.log(Helper.getDate(undefined) + " Pending : " + String(todoCount) + " Completed : " + String(doneCount));
  
}

exports.addTodo = addTodo;
exports.showTodo = showTodo;
exports.delTodo = delTodo;
exports.doneTodo = doneTodo;
exports.showHelp = showHelp;
exports.showReport = showReport;
/* os Not a pure module */
