// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var TodoManager = require("./todoManager.bs.js");

var command = Belt_Array.get(process.argv, 2);

var arg = Belt_Array.get(process.argv, 3);

var todoId = Belt_Option.flatMap(arg, Belt_Int.fromString);

if (command !== undefined) {
  var cmd = command.trim().toLowerCase();
  switch (cmd) {
    case "add" :
        TodoManager.addTodo(arg);
        break;
    case "del" :
        TodoManager.delTodo(todoId);
        break;
    case "done" :
        TodoManager.doneTodo(todoId);
        break;
    case "help" :
        TodoManager.showHelp(undefined);
        break;
    case "ls" :
        TodoManager.showTodo(undefined);
        break;
    case "report" :
        TodoManager.showReport(undefined);
        break;
    default:
      TodoManager.showHelp(undefined);
  }
} else {
  TodoManager.showHelp(undefined);
}

exports.command = command;
exports.arg = arg;
exports.todoId = todoId;
/* command Not a pure module */
